mybatis-plus:
  mapper-locations: classpath:config/*.xml


logging:
  level:
    org.springframework: info
    com.springboot: debug
    com.example: debug
  file: logs/project.log
spring:
    http:
      multipart:
        maxFileSize: 20MB
        maxRequestSize: 20MB

    datasource:
        name: testSQL
        url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&characterEncoding=utf-8&useSSL=true&createDatabaseIfNotExist=true
        username: root
        password: "root"
        type: com.alibaba.druid.pool.DruidDataSource
        platform: mysql
        driverClassName: com.mysql.cj.jdbc.Driver
        initialSize: 1
        minIdle: 1
        maxActive: 30
        #?????????????????
        maxWait: 60000
        # ???¨¹????¨°??????¦Ì??????????????????????¦Ë?????
        timeBetweenEvictionRunsMillis: 60000
        # ??????????????????§³??????????¦Ë?????
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        dbType: mysql
        #??PSCache??????????????????PSCache???§³
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 0
        # ???¨¹??????????filters????????????sql???????'wall'????????
        filters: stat,wall,slf4j
        # ???connectProperties????????mergeSql???????SQL???
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    thymeleaf:
        cache: false
server:
  port: 8088
